os: Visual Studio 2013
version: "{build}"
build: off

environment:
  matrix:
    - nodejs_version: 6

platform:
  - x64
  - x86

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm -g i npm@latest
  - set PATH=%APPDATA%\npm;%APPVEYOR_BUILD_FOLDER%\node_modules\.bin;%PATH%
  - npm install
  - for /f %%i in ('node -v') do set exact_nodejs_version=%%i
  - npm run minbuild
  - npm run pkgwinzip

artifacts:
  - path: dist\texpand-*.zip
    name: texpand


deploy:
    tag: $(appveyor_repo_tag_name)
    description: 'Windows build'
    provider: GitHub
    auth_token:
        secure: ZJL/17Jof5bsRgSkLn8Z6m91jdqr37KAHDm+xyEHCG1gFLKnht6Res9fdLDj6x44
    artifact: texpand
    draft: false
    prerelease: false
    on:
        appveyor_repo_tag: true
